{% set name = "optuna" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optuna-{{ version }}.tar.gz
  sha256: 04c3100a4fe88a71dc72f69d8a10ec9db7c9a0c884feaf932b68632b00686a8d

build:
  entry_points:
    - optuna = optuna.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - alembic
    - cliff
    - cmaes >=0.8.2
    - colorlog
    - numpy
    - packaging >=20.0
    - python >=3.6
    - pyyaml
    - scipy !=1.4.0
    - sqlalchemy >=1.1.0
    - tqdm

test:
  imports:
    - optuna
  commands:
    - pip check
    - optuna --help
  requires:
    - pip

about:
  home: https://optuna.org/
  summary: A hyperparameter optimization framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
